#!/usr/bin/env bash
# Must run from Helios root directory
cd /mnt/bn/voyager-sg-l3/zhexiao.xiong/Helios

MINICONDA_ROOT="/mnt/bn/voyager-sg-l3/zhexiao.xiong/miniconda3"
PYTHON_BIN="$MINICONDA_ROOT/bin/python3.13"
PY_MM="$("$PYTHON_BIN" -c "import sys; print(f'{sys.version_info.major}.{sys.version_info.minor}')")"
PY_SITE_PKGS="$MINICONDA_ROOT/lib/python${PY_MM}/site-packages"

export PATH="$MINICONDA_ROOT/bin:${PATH}"
export PYTHONNOUSERSITE=1
hash -r

export LD_LIBRARY_PATH="$PY_SITE_PKGS/nvidia/cudnn/lib:$PY_SITE_PKGS/nvidia/cusparselt/lib:${LD_LIBRARY_PATH}"
export PYTHONPATH="/mnt/bn/voyager-sg-l3/zhexiao.xiong/Helios:${PYTHONPATH}"

LOCAL_MODELS="/mnt/bn/voyager-sg-l3/zhexiao.xiong/Helios/BestWishYSH"

# ╔══════════════════════════════════════════════════════════════════╗
# ║  Helios 6-Stage Inference Pipeline (matches run.sh training)    ║
# ║                                                                  ║
# ║  Stage 1 (S1-init) ─┐                                           ║
# ║  Stage 2 (S1-post) ─┘→ Our-Helios-Base                          ║
# ║  Stage 3 (S2-init) ─┐                                           ║
# ║  Stage 4 (S2-post) ─┘→ Our-Helios-Mid                           ║
# ║  Stage 5 (S3-ode)  ─┐                                           ║
# ║  Stage 6 (S3-post) ─┘→ Our-Helios-Distilled                     ║
# ║                                                                  ║
# ║  For post stages (2/4/6), transformer_path should point to the   ║
# ║  merged transformer from the previous init stage. If it's a      ║
# ║  flat dir (no transformer/ subfolder), create a symlink:         ║
# ║    ln -s . <merged_dir>/transformer                              ║
# ╚══════════════════════════════════════════════════════════════════╝

# === Shared data paths ===
#
# Sekai: global captions (movement stripped) + per-video per-chunk actions from caption_original.
#   Generated by: python tools/preprocess_csv_global.py
SEKAI_CSV="data/Sekai-Project/train_global/sekai-real-walking-hq.csv,data/Sekai-Project/train_global/sekai-game-walking.csv,data/Sekai-Project/train_global/sekai-game-drone.csv"
SEKAI_FIRST_FRAME="data/yume_training/first_frame"
#
# Seadance: to get true per-chunk GT actions, run ONCE to export chunk_actions from PT files:
#   python tools/export_pt_chunk_actions.py \
#       --pt_dir  data/helios/seadance2_v3_helios_latents \
#       --csv_in  data/seadance2_yume_v3/world_model_action12_train_3000_simple1cam_actionfirst.tsv \
#       --csv_out data/seadance2_yume_v3/train_with_chunk_actions.csv
# Then set: SEADANCE_CSV="data/seadance2_yume_v3/train_with_chunk_actions.csv"
#
ACTION_CACHE="data/helios/action_embeds_cache.pt"


# ============================================================
# Stage 1 (S1-init): Learn chunk-autoregressive generation
#   Training: LoRA rank=128, LR=5e-5 on Helios-Base
#   Inference: 50 steps, guidance=5.0, no pyramid
#   base_model   = Helios-Base
#   transformer  = Helios-Base
# ============================================================
# CKPT_S1="ckpts/helios/20260330_205224/stage1_init/checkpoint-2000-final"
# TIMESTAMP_S1=$(date +%Y%m%d_%H%M%S)
# OUTPUT_DIR_S1="./output_helios/eval_sekai_stage1_s1init_${TIMESTAMP_S1}"

# torchrun --nproc_per_node 8 --master_port 9805 infer_helios.py \
#     --base_model_path "$LOCAL_MODELS/Helios-Base" \
#     --transformer_path "$LOCAL_MODELS/Helios-Base" \
#     --sample_type i2v \
#     --image_prompt_csv_path "$SEKAI_CSV" \
#     --base_image_prompt_path "$SEKAI_FIRST_FRAME" \
#     --action_embeds_cache "$ACTION_CACHE" \
#     --lora_path "$CKPT_S1" \
#     --partial_path "$CKPT_S1/transformer_partial.pth" \
#     --output_folder "$OUTPUT_DIR_S1" \
#     --num_frames 264 \
#     --height 384 \
#     --width 640 \
#     --num_inference_steps 50 \
#     --guidance_scale 5.0 \
#     --max_samples 40 \
#     --fps 24


# ============================================================
# Stage 2 (S1-post): Refine AR generation
#   Training: LoRA rank=128, LR=3e-5 on S1I_MERGED
#   Inference: 50 steps, guidance=5.0, no pyramid
#   → After merge produces: Our-Helios-Base
#   base_model   = Helios-Base
#   transformer  = S1I_MERGED (flat merged dir, no subfolder)
# ============================================================
# S1I_MERGED="ckpts/helios/20260330_205224/stage1_init/merged_transformer"
# CKPT_S2="ckpts/helios/20260330_205224/stage1_post/checkpoint-2000-final"
# TIMESTAMP_S2=$(date +%Y%m%d_%H%M%S)
# OUTPUT_DIR_S2="./output_helios/eval_sekai_stage2_s1post_${TIMESTAMP_S2}"

# torchrun --nproc_per_node 8 --master_port 9805 infer_helios.py \
#     --base_model_path "$LOCAL_MODELS/Helios-Base" \
#     --transformer_path "$S1I_MERGED" \
#     --sample_type i2v \
#     --image_prompt_csv_path "$SEKAI_CSV" \
#     --base_image_prompt_path "$SEKAI_FIRST_FRAME" \
#     --action_embeds_cache "$ACTION_CACHE" \
#     --lora_path "$CKPT_S2" \
#     --partial_path "$CKPT_S2/transformer_partial.pth" \
#     --output_folder "$OUTPUT_DIR_S2" \
#     --num_frames 264 \
#     --height 384 \
#     --width 640 \
#     --num_inference_steps 50 \
#     --guidance_scale 5.0 \
#     --max_samples 40 \
#     --fps 24

# ── Our-Helios-Base (S1-post merged, no LoRA) ─────────────────────────────────
# Evaluates the fully merged Our-Helios-Base model without any LoRA overhead.
# OUR_BASE="ckpts/helios/20260330_205224/stage1_post/merged_transformer"
# TIMESTAMP_BASE=$(date +%Y%m%d_%H%M%S)
# OUTPUT_DIR_BASE="./output_helios/eval_sekai_stage2_our_base_${TIMESTAMP_BASE}"

# torchrun --nproc_per_node 8 --master_port 9805 infer_helios.py \
#     --base_model_path "$LOCAL_MODELS/Helios-Base" \
#     --transformer_path "$OUR_BASE" \
#     --sample_type i2v \
#     --image_prompt_csv_path "$SEKAI_CSV" \
#     --base_image_prompt_path "$SEKAI_FIRST_FRAME" \
#     --action_embeds_cache "$ACTION_CACHE" \
#     --output_folder "$OUTPUT_DIR_BASE" \
#     --num_frames 264 \
#     --height 384 \
#     --width 640 \
#     --num_inference_steps 50 \
#     --guidance_scale 5.0 \
#     --max_samples 40 \
#     --fps 24


# ============================================================
# Stage 3 (S2-init): Learn pyramid distillation
#   Training: LoRA rank=256, LR=1e-4 on OUR_BASE
#   Inference: pyramid 20+20+20, guidance=5.0, cfg-zero
#   base_model   = Helios-Mid  (scheduler for pyramid)
#   transformer  = OUR_BASE    (Our-Helios-Base, flat merged dir)
# ============================================================
# OUR_BASE already set above
# S2I_CKPT="ckpts/helios/20260330_205224/stage2_init/checkpoint-2000-final"
# TIMESTAMP_S3=$(date +%Y%m%d_%H%M%S)
# OUTPUT_DIR_S3="./output_helios/eval_sekai_stage3_s2init_${TIMESTAMP_S3}"

# torchrun --nproc_per_node 8 --master_port 9805 infer_helios.py \
#     --base_model_path "$LOCAL_MODELS/Helios-Mid" \
#     --transformer_path "$OUR_BASE" \
#     --sample_type i2v \
#     --image_prompt_csv_path "$SEKAI_CSV" \
#     --base_image_prompt_path "$SEKAI_FIRST_FRAME" \
#     --action_embeds_cache "$ACTION_CACHE" \
#     --lora_path "$S2I_CKPT" \
#     --partial_path "$S2I_CKPT/transformer_partial.pth" \
#     --output_folder "$OUTPUT_DIR_S3" \
#     --num_frames 264 \
#     --height 384 \
#     --width 640 \
#     --guidance_scale 5.0 \
#     --is_enable_stage2 \
#     --pyramid_num_inference_steps_list 20 20 20 \
#     --use_zero_init \
#     --zero_steps 1 \
#     --max_samples 40 \
#     --fps 24

# ── S2I_MERGED (S2-init merged, no LoRA, pyramid) ─────────────────────────────
# S2I_MERGED="ckpts/helios/20260330_205224/stage2_init/merged_transformer"
# TIMESTAMP_S2M=$(date +%Y%m%d_%H%M%S)
# OUTPUT_DIR_S2M="./output_helios/eval_sekai_stage3_s2i_merged_${TIMESTAMP_S2M}"

# torchrun --nproc_per_node 8 --master_port 9805 infer_helios.py \
#     --base_model_path "$LOCAL_MODELS/Helios-Mid" \
#     --transformer_path "$S2I_MERGED" \
#     --sample_type i2v \
#     --image_prompt_csv_path "$SEKAI_CSV" \
#     --base_image_prompt_path "$SEKAI_FIRST_FRAME" \
#     --action_embeds_cache "$ACTION_CACHE" \
#     --output_folder "$OUTPUT_DIR_S2M" \
#     --num_frames 264 \
#     --height 384 \
#     --width 640 \
#     --guidance_scale 5.0 \
#     --is_enable_stage2 \
#     --pyramid_num_inference_steps_list 20 20 20 \
#     --use_zero_init \
#     --zero_steps 1 \
#     --max_samples 40 \
#     --fps 24


# ============================================================
# Stage 4 (S2-post): Refine pyramid distillation
#   Training: LoRA rank=256, LR=3e-5 on S2I_MERGED (+patch LoRA)
#   Inference: pyramid 20+20+20, guidance=5.0, cfg-zero
#   → After merge produces: Our-Helios-Mid
#   base_model   = Helios-Mid  (scheduler for pyramid)
#   transformer  = S2I_MERGED  (flat merged dir)
#   Note: stage2_post training still in progress (no final checkpoint yet)
# ============================================================
# S2P_CKPT="Helios/ckpts/helios/20260330_205224/stage2_post/checkpoint-2000-final"
# TIMESTAMP_S4=$(date +%Y%m%d_%H%M%S)
# OUTPUT_DIR_S4="./output_helios/eval_sekai_stage4_s2post_${TIMESTAMP_S4}"

# torchrun --nproc_per_node 8 --master_port 9805 infer_helios.py \
#     --base_model_path "$LOCAL_MODELS/Helios-Mid" \
#     --transformer_path "$S2I_MERGED" \
#     --sample_type i2v \
#     --image_prompt_csv_path "$SEKAI_CSV" \
#     --base_image_prompt_path "$SEKAI_FIRST_FRAME" \
#     --action_embeds_cache "$ACTION_CACHE" \
#     --lora_path "$S2P_CKPT" \
#     --partial_path "$S2P_CKPT/transformer_partial.pth" \
#     --output_folder "$OUTPUT_DIR_S4" \
#     --num_frames 264 \
#     --height 384 \
#     --width 640 \
#     --guidance_scale 5.0 \
#     --is_enable_stage2 \
#     --pyramid_num_inference_steps_list 20 20 20 \
#     --use_zero_init \
#     --zero_steps 1 \
#     --max_samples 40 \
#     --fps 24

# ── Our-Helios-Mid (S2-post merged, no LoRA) ──────────────────────────────────
# Evaluates the fully merged Our-Helios-Mid model without any LoRA overhead.
# OUR_MID="ckpts/helios/20260330_205224/stage2_post/merged_transformer"
# TIMESTAMP_MID=$(date +%Y%m%d_%H%M%S)
# OUTPUT_DIR_MID="./output_helios/eval_sekai_stage4_our_mid_${TIMESTAMP_MID}"

# torchrun --nproc_per_node 8 --master_port 9805 infer_helios.py \
#     --base_model_path "$LOCAL_MODELS/Helios-Mid" \
#     --transformer_path "$OUR_MID" \
#     --sample_type i2v \
#     --image_prompt_csv_path "$SEKAI_CSV" \
#     --base_image_prompt_path "$SEKAI_FIRST_FRAME" \
#     --action_embeds_cache "$ACTION_CACHE" \
#     --output_folder "$OUTPUT_DIR_MID" \
#     --num_frames 264 \
#     --height 384 \
#     --width 640 \
#     --guidance_scale 5.0 \
#     --is_enable_stage2 \
#     --pyramid_num_inference_steps_list 20 20 20 \
#     --use_zero_init \
#     --zero_steps 1 \
#     --max_samples 30 \
#     --fps 24


# ============================================================
# Stage 5 (S3-ode): ODE regression distillation
#   Training: LoRA rank=256, LR=2e-6 on OUR_MID (DeepSpeed ZeRO-2)
#   Inference: pyramid 2+2+2, guidance=1.0, amplify first chunk
#   base_model   = Helios-Distilled (scheduler for fast inference)
#   transformer  = OUR_MID          (Our-Helios-Mid, 需 transformer/ 子目录)
# ============================================================
# OUR_MID already set above (stage2_post/merged_transformer)
# CKPT_S5="ckpts/helios/.../stage3_ode/checkpoint-XXXX-final"
# TIMESTAMP_S5=$(date +%Y%m%d_%H%M%S)
# OUTPUT_DIR_S5="./output_helios/eval_sekai_stage5_s3ode_${TIMESTAMP_S5}"

# torchrun --nproc_per_node 8 --master_port 9805 infer_helios.py \
#     --base_model_path "$LOCAL_MODELS/Helios-Distilled" \
#     --transformer_path "$OUR_MID" \
#     --sample_type i2v \
#     --image_prompt_csv_path "$SEKAI_CSV" \
#     --base_image_prompt_path "$SEKAI_FIRST_FRAME" \
#     --action_embeds_cache "$ACTION_CACHE" \
#     --lora_path "$CKPT_S5" \
#     --partial_path "$CKPT_S5/transformer_partial.pth" \
#     --output_folder "$OUTPUT_DIR_S5" \
#     --num_frames 264 \
#     --height 384 \
#     --width 640 \
#     --guidance_scale 1.0 \
#     --is_enable_stage2 \
#     --pyramid_num_inference_steps_list 2 2 2 \
#     --is_amplify_first_chunk \
#     --max_samples 40 \
#     --fps 24


# ============================================================
# Stage 6 (S3-post): DMD adversarial distillation
#   Training: LoRA rank=256, LR=2e-6 on OUR_ODE (DeepSpeed ZeRO-2)
#   Inference: pyramid 2+2+2, guidance=1.0, amplify first chunk
#   → After merge produces: Our-Helios-Distilled
#   base_model   = Helios-Distilled (scheduler for fast inference)
#   transformer  = OUR_ODE          (需 transformer/ 子目录)
# ============================================================
# OUR_ODE="ckpts/helios/.../stage3_ode/merged_transformer"
# CKPT_S6="ckpts/helios/.../stage3_post/checkpoint-XXXX-final"
# TIMESTAMP_S6=$(date +%Y%m%d_%H%M%S)
# OUTPUT_DIR_S6="./output_helios/eval_sekai_stage6_s3post_${TIMESTAMP_S6}"

# torchrun --nproc_per_node 8 --master_port 9805 infer_helios.py \
#     --base_model_path "$LOCAL_MODELS/Helios-Distilled" \
#     --transformer_path "$OUR_ODE" \
#     --sample_type i2v \
#     --image_prompt_csv_path "$SEKAI_CSV" \
#     --base_image_prompt_path "$SEKAI_FIRST_FRAME" \
#     --action_embeds_cache "$ACTION_CACHE" \
#     --lora_path "$CKPT_S6" \
#     --partial_path "$CKPT_S6/transformer_partial.pth" \
#     --output_folder "$OUTPUT_DIR_S6" \
#     --num_frames 264 \
#     --height 384 \
#     --width 640 \
#     --guidance_scale 1.0 \
#     --is_enable_stage2 \
#     --pyramid_num_inference_steps_list 2 2 2 \
#     --is_amplify_first_chunk \
#     --max_samples 40 \
#     --fps 24


# ============================================================
# Ablation: Our-Helios-Base (S1-post merged), global prompt, NO action embedding
#   Uses the fully merged Our-Helios-Base transformer (no LoRA).
#   Prompt = movement-stripped global caption.
#   No --action_embeds_cache → no camera control embedding.
# ============================================================
# OUR_BASE_ABL="ckpts/helios/20260330_205224/stage1_post/merged_transformer"
# TIMESTAMP_ABL=$(date +%Y%m%d_%H%M%S)
# OUTPUT_DIR_ABL="./output_helios/eval_sekai_ablation_our_basestage1_no_action_embed_${TIMESTAMP_ABL}"

# torchrun --nproc_per_node 8 --master_port 9805 infer_helios.py \
#     --base_model_path "$LOCAL_MODELS/Helios-Base" \
#     --transformer_path "$OUR_BASE_ABL" \
#     --sample_type i2v \
#     --image_prompt_csv_path "$SEKAI_CSV" \
#     --base_image_prompt_path "$SEKAI_FIRST_FRAME" \
#     --output_folder "$OUTPUT_DIR_ABL" \
#     --num_frames 264 \
#     --height 384 \
#     --width 640 \
#     --num_inference_steps 50 \
#     --guidance_scale 5.0 \
#     --max_samples 40 \
#     --fps 24

# ============================================================
# Ablation: Vanilla Helios-Base (untrained), global prompt, NO action embedding
#   Pure baseline: original pretrained Helios-Base, no LoRA, no training,
#   no camera control embedding.
# ============================================================
TIMESTAMP_VANILLA=$(date +%Y%m%d_%H%M%S)
OUTPUT_DIR_VANILLA="./output_helios/eval_sekai_ablation_helios_base_vanilla_${TIMESTAMP_VANILLA}"

torchrun --nproc_per_node 8 --master_port 9805 infer_helios.py \
    --base_model_path "$LOCAL_MODELS/Helios-Base" \
    --transformer_path "$LOCAL_MODELS/Helios-Base" \
    --sample_type i2v \
    --image_prompt_csv_path "$SEKAI_CSV" \
    --base_image_prompt_path "$SEKAI_FIRST_FRAME" \
    --output_folder "$OUTPUT_DIR_VANILLA" \
    --num_frames 264 \
    --height 384 \
    --width 640 \
    --num_inference_steps 50 \
    --guidance_scale 5.0 \
    --max_samples 40 \
    --fps 24

cd /mnt/bn/voyager-sg-l3/zhexiao.xiong
python runner.py
